// Renderer for generated world JSON.
// Keeps pixel-art slicing + collision + depth conventions consistent with the current office scene.

export function renderWorld(scene, world, floorTexKeys) {
  const width = world.bounds.w;
  const height = world.bounds.h;
  const tileSize = world.tileSize || 16;

  // Floors by zone
  const base = scene.add.tileSprite(width / 2, height / 2, width, height, floorTexKeys.rooms).setDepth(0);
  base.setScrollFactor(0);

  const corridorZone = world.zones.find((z) => z.kind === 'corridor_dark');
  if (corridorZone) {
    scene.add.tileSprite(
      corridorZone.x + corridorZone.w / 2,
      corridorZone.y + corridorZone.h / 2,
      corridorZone.w,
      corridorZone.h,
      floorTexKeys.corridor
    ).setDepth(0.5);
  }

  const clinicZone = world.zones.find((z) => z.kind === 'clinic_blue');
  if (clinicZone) {
    scene.add.tileSprite(
      clinicZone.x + clinicZone.w / 2,
      clinicZone.y + clinicZone.h / 2,
      clinicZone.w,
      clinicZone.h,
      floorTexKeys.clinic
    ).setDepth(0.6);
  }

  // Outdoor chunks (street/park) - very simple floor fill for now
  for (const o of world.outdoor || []) {
    if (o.kind === 'street') {
      scene.add.tileSprite(o.x + o.w / 2, o.y + o.h / 2, o.w, o.h, floorTexKeys.corridor).setDepth(0.4);
    }
  }

  // Debug room fills (lightly) and collisions for corridors
  scene._obstacles = Array.isArray(scene._obstacles) ? scene._obstacles : [];

  // Corridors are walkable; walls are not yet generated by algorithm here.
  // Outdoor street is walkable.

  return { width, height };
}

