#!/usr/bin/env python3
"""Translate Chinese text in index.html (and other frontend files) to English."""
import re, os, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

BASE = r'C:\Users\zionv\OneDrive\Desktop\multbot\Star-Office-UI\frontend'

def process(path, replacements):
    with open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    for old, new in replacements:
        c = c.replace(old, new)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(c)
    n = len(re.findall(r'[\u4e00-\u9fff]', c))
    print(f'{os.path.basename(path)}: {n} remaining')
    if n and n < 30:
        for i, line in enumerate(c.split('\n'), 1):
            if re.search(r'[\u4e00-\u9fff]', line):
                print(f'  L{i}: {line.strip()[:120]}')

# ─── index.html ─────────────────────────────────────────────────────────────
index_path = os.path.join(BASE, 'index.html')
idx_repl = [
    # Title / skeleton
    ('Star 的像素Office', "Star's Pixel Office"),
    ('正在进入像素Office…', 'Loading Pixel Office…'),
    # Panel titles
    ('昨 日 小 记', 'Yesterday Memo'),
    ('访 客 列 表', 'Guest List'),
    ('正在加载访客...', 'Loading guests...'),
    ('暂无昨日日记', 'No memo for yesterday'),
    ("console.error('加载 memo 失败:', e);", "console.error('Failed to load memo:', e);"),
    ('加载失败', 'Failed to load'),
    ('正在加载 Star 的像素办公室...', "Loading Star's pixel office..."),
    ('正在打包虾头……', 'Packing up…'),
    # Asset drawer
    ('装修房间 · 资产Sidebar', 'Room Decor · Asset Sidebar'),
    ('装修房间', 'Decor Room'),
    ('资产管理', 'Asset Manager'),
    ('请输入装修Verify码', 'Enter decor passcode'),
    ('输入Verify码', 'Enter passcode'),
    ('搬新家', 'Move In'),
    ('回老家', 'Restore Default'),
    ('找中介', 'AI Design'),
    ('自己装', 'DIY'),
    ('生成模式', 'Generation Mode'),
    ('可选：填写你的生图 API Key（留空不影响基础功能）', 'Optional: enter your image generation API Key (core features work without it)'),
    ('粘贴 GEMINI_API_KEY（不会回显）', 'Paste GEMINI_API_KEY (will not be shown)'),
    ('按中介方案搬家', 'Generate with AI Design'),
    ('回上一个家', 'Restore Previous'),
    ('Favorite这个家', 'Save Favorite'),
    ('Favorite的家', 'Saved Favorites'),
    ('搜索资产名（如 desk / sofa / star）', 'Search asset name (e.g. desk / sofa / star)'),
    ('Upload素材', 'Upload Asset'),
    ('Confirm刷新', 'Confirm & Refresh'),
    ('Reset默认', 'Reset Default'),
    ('恢复上版', 'Restore Prev'),
    ('移动视野', 'Pan View'),
    ('锁定视野', 'Lock View'),
    # Language strings (zh block)
    ("btnIdle: '待命'", "btnIdle: 'Idle'"),
    ("btnWork: '工作'", "btnWork: 'Work'"),
    ("btnSync: '同步'", "btnSync: 'Sync'"),
    ("btnError: '报警'", "btnError: 'Alert'"),
    ("btnDecor: '装修房间'", "btnDecor: 'Decor Room'"),
    ("drawerTitle: '装修房间 · 资产Sidebar'", "drawerTitle: 'Room Decor · Asset Sidebar'"),
    ("authTitle: '请输入装修Verify码'", "authTitle: 'Enter decor passcode'"),
    ("authPlaceholder: '输入Verify码'", "authPlaceholder: 'Enter passcode'"),
    ("authDefaultPassHint: '默认Password：1234（可随时", "authDefaultPassHint: 'Default password: 1234 (can be changed"),
    ("drawerVisibilityTip: '可见性：点击条目右侧眼睛按钮切换该资产显示'", "drawerVisibilityTip: 'Visibility: click the eye button on the right to toggle asset display'"),
    ("hideDrawer: '👁 隐藏Sidebar'", "hideDrawer: '👁 Hide Sidebar'"),
    ("showDrawer: '👁 显示Sidebar'", "showDrawer: '👁 Show Sidebar'"),
    ("assetHide: '隐藏'", "assetHide: 'Hide'"),
    ("assetShow: '显示'", "assetShow: 'Show'"),
    ("resetToDefault: 'Reset为默认资产'", "resetToDefault: 'Reset to Default Asset'"),
    ("restorePrevAsset: '用上一版'", "restorePrevAsset: 'Use Previous Version'"),
    ("btnMove: '📦 搬新家'", "btnMove: '📦 Move In'"),
    ("btnHome: '🐚 回老家'", "btnHome: '🐚 Restore Default'"),
    ("btnHomeLast: '↩️ 回上一个家'", "btnHomeLast: '↩️ Restore Previous'"),
    ("btnHomeFavorite: '⭐ Favorite这个家'", "btnHomeFavorite: '⭐ Save Favorite'"),
    ("btnBroker: '🤝 找中介'", "btnBroker: '🤝 AI Design'"),
    ("homeFavTitle: '🏠 Favorite的家'", "homeFavTitle: '🏠 Saved Favorites'"),
    ("homeFavEmpty: '还没有Favorite，先点", "homeFavEmpty: 'No favorites yet, click"),
    ("homeFavApply: '替换到当前地图'", "homeFavApply: 'Apply to Current Map'"),
    ("homeFavDelete: '删除", "homeFavDelete: 'Delete"),
    ("brokerHint: '你会给龙虾推荐什么样的房子'", "brokerHint: 'What kind of room would you suggest?'"),
    ("brokerPromptPh: '例如：故宫主题、莫奈风格、地牢主题、兵马俑主题……'", "brokerPromptPh: 'e.g. Cyberpunk Tokyo, Monet style, dungeon theme, ancient ruins…'"),
    ("brokerNeedPrompt: '请先输入中介方案描述'", "brokerNeedPrompt: 'Please enter a room design description first'"),
    ("brokerGenerating: '🏘️ 正在按中介方案生成底图，请稍候（约20-90秒）...'", "brokerGenerating: '🏘️ Generating room with AI design (20–90 seconds)...'"),
    ("brokerDone: '✅ 已按中介方案生成并替换底图，正在刷新房间...'", "brokerDone: '✅ AI design applied, refreshing room...'"),
    ("moveSuccess: '✅ 搬家Success！'", "moveSuccess: '✅ Move-in Success!'"),
    ("brokerMissingKey: '❌ 生图失败：缺少 GEMINI API Key，请在下方填写并Save后重试'", "brokerMissingKey: '❌ Generation failed: missing GEMINI API Key, please enter and save it below'"),
    ("geminiPanelTitle: '🔐 API Settings（可折叠）'", "geminiPanelTitle: '🔐 API Settings (collapsible)'"),
    ("geminiHint: '可选：填写你的生图 API Key（留空不影响基础功能）'", "geminiHint: 'Optional: enter your image generation API Key (core features work without it)'"),
    ("geminiApiDoc: '📘 如何申请 Google API Ke", "geminiApiDoc: '📘 How to get a Google API Ke"),
    ("speedModeLabel: '生成模式'", "speedModeLabel: 'Generation Mode'"),
    ("searchPlaceholder: '搜索资产名（如 desk / sofa / star）'", "searchPlaceholder: 'Search asset name (e.g. desk / sofa / star)'"),
    ("loaded: '已加载'", "loaded: 'Loaded'"),
    ("allAssets: '全部资产'", "allAssets: 'All Assets'"),
    ("chooseImage: 'Upload素材'", "chooseImage: 'Upload Asset'"),
    ("confirmUpload: 'Confirm刷新'", "confirmUpload: 'Confirm & Refresh'"),
    ("resetToDefault: 'Reset默认'", "resetToDefault: 'Reset Default'"),
    ("restorePrevAsset: '恢复上版'", "restorePrevAsset: 'Restore Prev'"),
    ("uploadPending:", "uploadPending:"),  # keep as-is if already partially English
    ("assetHintNotInScene: '当前Scene未检测到此对象，仍可替换文件（刷新后生效）'", "assetHintNotInScene: 'Object not detected in current scene; you can still replace the file (takes effect after refresh)'"),
    ("assetHintDefault: '通用素材：建议保持原图尺寸、透明通道与视觉重心一致，避免错位或失真'", "assetHintDefault: 'General asset: keep original size, transparency, and visual anchor consistent to avoid misalignment'"),
    ("memoTitle: '昨 日 小 记'", "memoTitle: 'Yesterday Memo'"),
    ("guestTitle: '访 客 列 表'", "guestTitle: 'Guest List'"),
    ("officeTitle: 'Star", "officeTitle: 'Star"),
    ("loadingOffice: 'Star のピクセルオフィスを読み込み中...'", "loadingOffice: \"Loading Star's pixel office...\""),
    # Comments
    ('// 简易中English切换', '// Simple language switcher'),
    ('// Language切换后立即重绘资产侧栏，确保易懂名同步更新', '// After language change, immediately redraw asset sidebar to sync display names'),
    ('// Language切换后同步刷新已选资产的指导文案（Upload区小字三语联动）', '// After language change, refresh selected asset hint text'),
    ('// Language切换时，当前正在显示的 loading 文案也实时切换', '// After language change, update any currently visible loading text'),
    ('// 检测浏览器是否支持 WebP', '// Detect browser WebP support'),
    ('// 方法 1: 使用 canvas 检测', '// Method 1: detect via canvas'),
    ('// 方法 2: 使用 image 检测（备用）', '// Method 2: detect via image (fallback)'),
    ('// 桌面端保持 FIT；手机端用 RESIZE，并在相机里按高度做 fit（可横向 pan）', '// Desktop: FIT mode; mobile: RESIZE with height fit (horizontal pan enabled)'),
    ('// Memo 相关函数', '// Memo functions'),
    ('// 更新加载进度', '// Update loading progress'),
    ('// 隐藏加载界面', '// Hide loading overlay'),
    ('// Phaser 就绪后，移除首屏骨架，避免黑屏感', '// After Phaser is ready, remove skeleton screen to avoid black flash'),
    ('// 兜底：某些移动网络/CDN 抖动时，避免一直卡在"加载中"遮罩', '// Fallback: on flaky mobile/CDN, avoid getting stuck on loading overlay'),
    ('// 懒加载逻辑已Cancel（体验优先：Decoration首屏直接出现）', '// Lazy load cancelled (UX priority: decorations appear immediately)'),
    # States (duplicated in index.html)
    ("idle: { name: '待命'", "idle: { name: 'Idle'"),
    ("writing: { name: '整理文档'", "writing: { name: 'Writing'"),
    ("researching: { name: '搜索信息'", "researching: { name: 'Researching'"),
    ("executing: { name: '执行任务'", "executing: { name: 'Executing'"),
    ("syncing: { name: '同步备份'", "syncing: { name: 'Syncing'"),
    ("error: { name: '出错了'", "error: { name: 'Error'"),
    # Bubble texts (zh, duplicated)
    ('待命中：耳朵竖起来了', 'On standby: ears perked up'),
    ('我在这儿，随时可以开工', 'Right here, ready to roll'),
    ('先把桌面收拾干净再说', 'Clearing the desk before we start'),
    ('呼——给大脑放个风', 'Ahhh — giving the brain a breather'),
    ('今天也要优雅地高效', 'Staying elegantly efficient today'),
    ('等待，是为了更准确的一击', 'Waiting for the perfect moment to strike'),
    ('咖啡还热，灵感也还在', 'Coffee is still hot, so is the inspiration'),
    ('我在后台给你加 Buff', 'Buffing you up in the background'),
    ('状态：静心 / 充电', 'Status: resting / recharging'),
    ('小猫说：慢一点也没关系', 'The cat says: it is okay to slow down'),
    ('进入专注模式：勿扰', 'Entering focus mode: do not disturb'),
    ('先把关键路径跑通', 'Getting the critical path working first'),
    ('我来把复杂变简单', 'Turning complexity into simplicity'),
    ('把 bug 关进笼子里', 'Caging that bug'),
    ('写到一半，先Save', 'Halfway through — saving now'),
    ('写到一半，先保存', 'Halfway through — saving now'),
    ('把每一步都做成可回滚', 'Making every step reversible'),
    ("今天的进度，明天的底气", "Today's progress is tomorrow's confidence"),
    ('先收敛，再发散', 'Converge first, diverge later'),
    ('让系统变得更可解释', 'Making the system more explainable'),
    ('稳住，我们能赢', 'Stay steady, we got this'),
    ('我在挖证据链', 'Digging through the evidence chain'),
    ('让我把信息熬成结论', 'Distilling information into conclusions'),
    ('找到了：关键在这里', 'Found it: the key is right here'),
    ('先把变量控制住', 'Getting the variables under control'),
    ('我在查：它为什么会这样', 'Investigating: why is this happening'),
    ('把直觉写成Verify', 'Turning intuition into proof'),
    ('把直觉写成验证', 'Turning intuition into proof'),
    ('先定位，再优化', 'Locate first, optimize later'),
    ('别急，先画因果图', 'Hold on — drawing the causal diagram first'),
    ('执行中：不要眨眼', 'Executing: do not blink'),
    ('把任务切成小块逐个击破', 'Breaking the task into chunks and tackling each one'),
    ('开始跑 pipeline', 'Kicking off the pipeline'),
    ('一键推进：走你', "One-click advance: let's go"),
    ('让结果自己说话', 'Letting the results speak for themselves'),
    ('先做最小可行，再做最美版本', 'Build the minimum viable first, then make it beautiful'),
    ('同步中：把今天锁进云里', 'Syncing: locking today into the cloud'),
    ('备份不是仪式，是安全感', 'Backup is not a ritual — it is peace of mind'),
    ('写入中…别断电', 'Writing… do not cut the power'),
    ('把变更交给时间戳', 'Handing changes over to the timestamp'),
    ('云端对齐：咔哒', 'Cloud aligned: click'),
    ('同步完成前先别乱动', 'Hold still until sync finishes'),
    ('把未来的自己从灾难里救出来', 'Saving your future self from disaster'),
    ('多一份备份，少一份后悔', 'One more backup, one less regret'),
    ('警报响了：先别慌', 'Alert triggered: stay calm first'),
    ('我闻到 bug 的味道了', 'I can smell a bug nearby'),
    ('先复现，再谈修复', 'Reproduce it first, then talk about fixing'),
    ('把日志给我，我会说人话', "Give me the logs — I'll translate them"),
    ('Error不是敌人，是线索', 'Errors are not enemies — they are clues'),
    ('错误不是敌人，是线索', 'Errors are not enemies — they are clues'),
    ('把影响面圈起来', 'Circling the blast radius'),
    ('先止血，再手术', 'Stop the bleeding first, then operate'),
    ('我在：马上定位根因', 'On it: finding the root cause now'),
    ('别怕，这种我见多了', 'Do not worry — seen this a hundred times'),
    ('报警中：让问题自己现形', 'Alarming: letting the bug reveal itself'),
    ('喵~', 'Meow~'),
    ('咕噜咕噜…', 'Purrrr...'),
    ('尾巴摇一摇', 'Swishing my tail'),
    ('晒太阳最开心', 'Sunbathing is the best'),
    ('有人来看我啦', 'Someone came to see me!'),
    ('我是这个Office的吉祥物', 'I am the office mascot'),
    ('伸个懒腰', 'Stretching out'),
    ("今天的罐罐准备好了吗", "Is today's treat ready?"),
    ('呼噜呼噜', 'Purrr purrr'),
    ('这个位置视野最好', 'Best view in the office'),
    # Asset name map (zh)
    ("'star-idle-v5': '主角·待命Status'", "'star-idle-v5': 'Main · Idle'"),
    ("'star-working-spritesheet-grid': '主角·工作Status'", "'star-working-spritesheet-grid': 'Main · Working'"),
    ("'sync-animation': '主角·同步Status'", "'sync-animation': 'Main · Syncing'"),
    ("'sync-animation-v3-grid': '主角·同步Status'", "'sync-animation-v3-grid': 'Main · Syncing'"),
    ("'error-bug-spritesheet-grid': '主角·报错Status'", "'error-bug-spritesheet-grid': 'Main · Error'"),
    ("'cats-spritesheet': '随机猫猫'", "'cats-spritesheet': 'Random Cat'"),
    ("'coffee-machine-v3-grid': '咖啡机'", "'coffee-machine-v3-grid': 'Coffee Machine'"),
    ("'coffee-machine-shadow-v1': '咖啡机阴影'", "'coffee-machine-shadow-v1': 'Coffee Machine Shadow'"),
    ("'posters-spritesheet': '随机海报'", "'posters-spritesheet': 'Random Poster'"),
    ("'serverroom-spritesheet': '服务器房动画'", "'serverroom-spritesheet': 'Server Room Animation'"),
    ("'plants-spritesheet': '随机绿植'", "'plants-spritesheet': 'Random Plant'"),
    ("'flowers-bloom-v2': '随机花朵'", "'flowers-bloom-v2': 'Random Flower'"),
    ("'office_bg_small': 'Office背景'", "'office_bg_small': 'Office Background'"),
    ("'memo-bg': 'Yesterday Memo底图'", "'memo-bg': 'Memo Background'"),
    ("'desk-v3': '办公桌'", "'desk-v3': 'Desk'"),
    ("'desk': '办公桌（旧）'", "'desk': 'Desk (Legacy)'"),
    ("'guest_anim_1': '访客动画 1'", "'guest_anim_1': 'Guest Animation 1'"),
    ("'guest_anim_2': '访客动画 2'", "'guest_anim_2': 'Guest Animation 2'"),
    ("'guest_anim_3': '访客动画 3'", "'guest_anim_3': 'Guest Animation 3'"),
    ("'guest_anim_4': '访客动画 4'", "'guest_anim_4': 'Guest Animation 4'"),
    ("'guest_anim_5': '访客动画 5'", "'guest_anim_5': 'Guest Animation 5'"),
    ("'guest_anim_6': '访客动画 6'", "'guest_anim_6': 'Guest Animation 6'"),
    # Asset hints (zh)
    ("'office_bg_small': '主Scene底图（当前生效）。建议 1280×720（16:9），保留房间结构与视角，避免Character站位错位。'",
     "'office_bg_small': 'Main background (active). Recommend 1280×720 (16:9), preserve room structure and camera angle to avoid character misalignment.'"),
    ("'office_bg': '历史背景备份。通常不直接生效，建议与 office_bg_small 保持同构图用于Rollback。'",
     "'office_bg': 'Historical background backup. Usually not active; keep same composition as office_bg_small for rollback.'"),
    ("'star-idle-v5': '主角待机动画表。请保持 256×256 分帧与网格布局一致，否则待机动作会错帧。'",
     "'star-idle-v5': 'Main character idle spritesheet. Keep 256×256 frame grid consistent, or idle animation will desync.'"),
    ("'star-working-spritesheet-grid': '主角工作动画表（工位Status）。请保持 300×300 分帧，建议人物重心与原图一致。'",
     "'star-working-spritesheet-grid': 'Main character working spritesheet (desk state). Keep 300×300 frames, align visual anchor.'"),
    ("'sync-animation': '同步Status素材（当前引用）。建议按 256×256 帧规范制作，避免同步Status显示静止或抖动。'",
     "'sync-animation': 'Sync state asset (currently referenced). Use 256×256 frames to avoid freeze or jitter.'"),
    ("'sync-animation-v3-grid': '同步动画表（兼容资源）。保持 256×256 网格可用于替换同步动作细节。'",
     "'sync-animation-v3-grid': 'Sync animation (compat). Keep 256×256 grid for detail replacement.'"),
    ("'error-bug-spritesheet-grid': '报错Status动画表。请保持 220×220 分帧，建议高对比度以增强异常提示感。'",
     "'error-bug-spritesheet-grid': 'Error state spritesheet. Keep 220×220 frames; use high contrast for visibility.'"),
    ("'desk-v3': '办公桌前景层。影响主角前后遮挡关系，建议保持当前比例与锚点视觉重心。'",
     "'desk-v3': 'Desk foreground layer. Affects character depth order; keep current scale and visual anchor.'"),
    ("'desk': '旧版办公桌素材（兼容用）。建议与 desk-v3 保持相近体积与锚点，避免遮挡异常。'",
     "'desk': 'Legacy desk asset (compat). Keep similar size and anchor to desk-v3 to avoid depth issues.'"),
    ("'sofa-idle-v3': '沙发静态素材。建议保持 256×256 与透明背景，避免替换后位置漂移。'",
     "'sofa-idle-v3': 'Sofa static asset. Keep 256×256 with transparent background to prevent position drift.'"),
    ("'sofa-shadow-v1': '沙发阴影层。建议与沙发主体同坐标叠放，增强贴地感。'",
     "'sofa-shadow-v1': 'Sofa shadow layer. Overlay at same coordinates as sofa for grounded look.'"),
    ("'memo-bg': '小记面板底图。建议留出文字阅读区域，降低高频纹理，避免信息难读。'",
     "'memo-bg': 'Memo panel background. Leave readable text area; avoid high-frequency textures.'"),
    ("'plants-spritesheet': '绿植随机素材。保持 160×160 分帧，可一次替换多个绿植位的观感。'",
     "'plants-spritesheet': 'Plant random asset. Keep 160×160 frames to update all plant positions at once.'"),
    ("'posters-spritesheet': '海报随机素材。保持 160×160 分帧，建议统一风格避免墙面杂乱。'",
     "'posters-spritesheet': 'Poster random asset. Keep 160×160 frames; unify style to avoid cluttered walls.'"),
    ("'cats-spritesheet': '猫咪随机素材。保持 160×160 分帧，建议轮廓清晰、识别度高。'",
     "'cats-spritesheet': 'Cat random asset. Keep 160×160 frames; clear silhouette recommended.'"),
    ("'coffee-machine-v3-grid': '咖啡机静态素材。建议保持 230×230 与当前锚点，避免位置偏移。'",
     "'coffee-machine-v3-grid': 'Coffee machine asset. Keep 230×230 and current anchor to avoid position drift.'"),
    ("'coffee-machine-shadow-v1': '咖啡机阴影层。建议与咖啡机本体同宽对齐，增强贴地感。'",
     "'coffee-machine-shadow-v1': 'Coffee machine shadow. Align width with machine body for grounded look.'"),
    ("'serverroom-spritesheet': '服务器房动画表。保持 180×251 分帧，灯效变化建议节奏均匀不过闪。'",
     "'serverroom-spritesheet': 'Server room animation. Keep 180×251 frames; use steady light rhythm, avoid strobing.'"),
    ("'flowers-bloom-v2': '花朵随机素材。保持 128×128 分帧，建议色彩与整体Office主色协调。'",
     "'flowers-bloom-v2': 'Flower random asset. Keep 128×128 frames; coordinate colors with overall office palette.'"),
    ("'guest_anim_1': '访客动画序列 1（32×32 分帧）。建议保持像素风、轮廓清晰，与主角风格统一。'",
     "'guest_anim_1': 'Guest animation set 1 (32×32 frames). Keep pixel style, clear outline, consistent with main character.'"),
    ("'guest_anim_2': '访客动画序列 2（32×32 分帧）。建议保持像素风、轮廓清晰，与主角风格统一。'",
     "'guest_anim_2': 'Guest animation set 2 (32×32 frames). Keep pixel style, clear outline, consistent with main character.'"),
    ("'guest_anim_3': '访客动画序列 3（32×32 分帧）。建议保持像素风、轮廓清晰，与主角风格统一。'",
     "'guest_anim_3': 'Guest animation set 3 (32×32 frames). Keep pixel style, clear outline, consistent with main character.'"),
    ("'guest_anim_4': '访客动画序列 4（32×32 分帧）。建议保持像素风、轮廓清晰，与主角风格统一。'",
     "'guest_anim_4': 'Guest animation set 4 (32×32 frames). Keep pixel style, clear outline, consistent with main character.'"),
    ("'guest_anim_5': '访客动画序列 5（32×32 分帧）。建议保持像素风、轮廓清晰，与主角风格统一。'",
     "'guest_anim_5': 'Guest animation set 5 (32×32 frames). Keep pixel style, clear outline, consistent with main character.'"),
    ("'guest_anim_6': '访客动画序列 6（32×32 分帧）。建议保持像素风、轮廓清晰，与主角风格统一。'",
     "'guest_anim_6': 'Guest animation set 6 (32×32 frames). Keep pixel style, clear outline, consistent with main character.'"),
    ("'guest_role_1': '访客静态形象备用图 1。建议与对应 guest_anim Character设定一致，避免切换割裂。'",
     "'guest_role_1': 'Guest static fallback 1. Keep consistent with guest_anim design to avoid visual discontinuity.'"),
    ("'guest_role_2': '访客静态形象备用图 2。建议与对应 guest_anim Character设定一致，避免切换割裂。'",
     "'guest_role_2': 'Guest static fallback 2. Keep consistent with guest_anim design to avoid visual discontinuity.'"),
    ("'guest_role_3': '访客静态形象备用图 3。建议与对应 guest_anim Character设定一致，避免切换割裂。'",
     "'guest_role_3': 'Guest static fallback 3. Keep consistent with guest_anim design to avoid visual discontinuity.'"),
    ("'guest_role_4': '访客静态形象备用图 4。建议与对应 guest_anim Character设定一致，避免切换割裂。'",
     "'guest_role_4': 'Guest static fallback 4. Keep consistent with guest_anim design to avoid visual discontinuity.'"),
    ("'guest_role_5': '访客静态形象备用图 5。建议与对应 guest_anim Character设定一致，避免切换割裂。'",
     "'guest_role_5': 'Guest static fallback 5. Keep consistent with guest_anim design to avoid visual discontinuity.'"),
    ("'guest_role_6': '访客静态形象备用图 6。建议与对应 guest_anim Character设定一致，避免切换割裂。'",
     "'guest_role_6': 'Guest static fallback 6. Keep consistent with guest_anim design to avoid visual discontinuity.'"),
    # Loading messages (zh)
    ('正在打包今天的灵感行李……', 'Packing up today\'s inspiration…'),
    ('正在抽取下一站数字坐标……', 'Extracting next digital coordinates…'),
    ('正在查看本次漂流目的地……', 'Checking this journey\'s destination…'),
    ('正在把Office折叠成随身模式……', 'Folding the office into portable mode…'),
    ('正在给钳子装上远行 Buff……', 'Installing travel buff on the lobster…'),
    ('正在匹配下一段创作气候……', 'Matching next creative climate…'),
    ('正在把时差调成冒险模式……', 'Setting timezone to adventure mode…'),
    ('正在接收陌生街区的 Wi‑Fi 心跳……', 'Catching Wi‑Fi heartbeat from unknown streets…'),
    ('正在试播下一站的海风 BGM……', 'Playing a preview of the next destination\'s ocean breeze BGM…'),
    ('正在加载"也许会爱上"的新房间……', 'Loading a room you might just fall in love with…'),
    ('正在为未知邻居准备自我介绍……', 'Preparing an intro for unknown neighbors…'),
    ('正在解锁下一片数字海域……', 'Unlocking the next digital sea…'),
    ('正在把好奇心调到满格……', 'Charging curiosity to maximum…'),
    ('正在等待旅程投递下一张门牌号……', 'Waiting for the journey to deliver the next address…'),
    # Misc UI
    ('if (msg) msg.textContent = \'❌ 请输入Verify码\';', "if (msg) msg.textContent = '❌ Please enter the passcode';"),
    ('if (msg) msg.textContent = \'✅ Verify通过\';', "if (msg) msg.textContent = '✅ Verified successfully';"),
    ('if (msg) msg.textContent = \'❌ Verify码Error\';', "if (msg) msg.textContent = '❌ Incorrect passcode';"),
    ('if (msg) msg.textContent = `❌ Verify失败：${e}`;', "if (msg) msg.textContent = `❌ Verification failed: ${e}`;"),
    ("'star-idle-v5': '主角·待命Status',", "'star-idle-v5': 'Main · Idle',"),
    # Asset list feedback
    ('暂无资产（可点\u201c刷新\u201d重试）', 'No assets found (click Refresh to retry)'),
    ("'已隐藏'", "'Hidden'"),
    ("已加载资产：${assetListData.length} ｜ Scene抓取：${sceneAssetItems.length}", "Loaded assets: ${assetListData.length} | Scene captured: ${sceneAssetItems.length}"),
    ("console.error('加载资产列表失败', e);", "console.error('Failed to load asset list', e);"),
    ('❌ 资产加载失败，请点\u201c刷新\u201d重试', '❌ Asset load failed, click Refresh to retry'),
    ("请先选中一个资产路径", "Please select an asset path first"),
    ("⏳ 正在Upload并替换，请稍候...", "⏳ Uploading and replacing, please wait..."),
    ("❌ 更新失败：${data.msg || res.status}", "❌ Update failed: ${data.msg || res.status}"),
    # Confirm dialogs
    ("✅ 已生成并替换底图，正在刷新房间...", "✅ Background generated and replaced, refreshing room..."),
    ("✅ 已生成并替换底图（局部刷新失败，可手动刷新页面）", "✅ Background replaced (partial refresh failed, refresh the page manually)"),
    ("❌ 生成失败：${e}", "❌ Generation failed: ${e}"),
    ("function setWorkingStatus(detail = '工作中')", "function setWorkingStatus(detail = 'Working')"),
    ("if (msg) msg.textContent = '请输入有效 API Key';", "if (msg) msg.textContent = 'Please enter a valid API Key';"),
    ("if (msg) msg.textContent = `Save失败：${data.msg || res.status}`;", "if (msg) msg.textContent = `Save failed: ${data.msg || res.status}`;"),
    ("if (msg) msg.textContent = '✅ 已Save，可重新点击搬家/中介';", "if (msg) msg.textContent = '✅ Saved. You can now click Move In or AI Design.';"),
    ("if (msg) msg.textContent = `Save失败：${e}`;", "if (msg) msg.textContent = `Save failed: ${e}`;"),
    ("out.textContent = progressMsg + '（已等待 ' + elapsed + '秒）'", "out.textContent = progressMsg + ' (waited ' + elapsed + 's)'"),
    ("return { ok: false, msg: '生图超时（超过5分钟），请重试' };", "return { ok: false, msg: 'Image generation timed out (over 5 minutes), please retry' };"),
    ("out.textContent = '❌ 当前 API Key 已失效/疑似泄露，请更换新 Key 后重试';", "out.textContent = '❌ Current API Key is invalid or may be leaked, please replace it';"),
    ("out.textContent = '❌ 当前Model在此通道不可用，请切换可用Model后重试'", "out.textContent = '❌ Current model unavailable on this channel, please switch models'"),
    ("详情：' + data.detail", "Details: ' + data.detail"),
    ("out.textContent = `❌ 生成失败：${data.msg || 'unknown error'}`;", "out.textContent = `❌ Generation failed: ${data.msg || 'unknown error'}`;"),
    ("setWorkingStatus('正在处理中介装修方案');", "setWorkingStatus('Processing AI design request');"),
    ("'🏘️ 正在按中介方案生成底图'", "'🏘️ Generating room with AI design'"),
    ("setWorkingStatus('正在搬新家');", "setWorkingStatus('Moving in');"),
    ("out.textContent = '🧳 正在打包行李，请稍后（约30~120秒）';", "out.textContent = '🧳 Packing up, please wait (30–120 seconds)';"),
    ("'🧳 正在生成新房间'", "'🧳 Generating new room'"),
    ("out.textContent = '✅ 已恢复初始底图';", "out.textContent = '✅ Default background restored';"),
    ("out.textContent = `❌ 恢复失败：${data.msg || res.status}`;", "out.textContent = `❌ Restore failed: ${data.msg || res.status}`;"),
    ("out.textContent = '✅ 已恢复初始底图（局部刷新失败，可手动刷新页面）';", "out.textContent = '✅ Default background restored (partial refresh failed, refresh manually)';"),
    ("out.textContent = `❌ 恢复失败：${e}`;", "out.textContent = `❌ Restore failed: ${e}`;"),
    ("const confirmMsg = '⚠️ 回老家会覆盖当前自定义房间背景（可从 bg-history 恢复历史图）。\\n确定继续吗？';", "const confirmMsg = '⚠️ Restoring will overwrite the current custom background (recoverable from bg-history).\\nContinue?';"),
    ("out.textContent = '已Cancel回老家';", "out.textContent = 'Restore cancelled';"),
    ("setWorkingStatus('正在回老家');", "setWorkingStatus('Restoring default background');"),
    ("out.textContent = '🏡 正在回老家（恢复初始底图）...';", "out.textContent = '🏡 Restoring default background...';"),
    ("const confirmMsg = '⚠️ 将Rollback到最近一次生成的房间背景，确定继续吗？';", "const confirmMsg = '⚠️ This will roll back to the most recently generated background. Continue?';"),
    ("out.textContent = '已CancelRollback';", "out.textContent = 'Rollback cancelled';"),
    ("setWorkingStatus('正在Rollback到上一次背景');", "setWorkingStatus('Rolling back to previous background');"),
    ("out.textContent = '↩️ 正在Rollback到最近一次生成底图...';", "out.textContent = '↩️ Rolling back to most recently generated background...';"),
    ("out.textContent = `❌ Rollback失败：${data.msg || res.status}`;", "out.textContent = `❌ Rollback failed: ${data.msg || res.status}`;"),
    ("out.textContent = '✅ 已Rollback到上一次背景';", "out.textContent = '✅ Rolled back to previous background';"),
    ("out.textContent = '✅ 已Rollback到上一次背景（局部刷新失败，可手动刷新页面）';", "out.textContent = '✅ Rolled back (partial refresh failed, refresh manually)';"),
    ("try { setState('idle', '已Rollback到上一次背景'); } catch (e) {}", "try { setState('idle', 'Rolled back to previous background'); } catch (e) {}"),
    ("out.textContent = `❌ Rollback失败：${e}`;", "out.textContent = `❌ Rollback failed: ${e}`;"),
    ("throw new Error(`接口未返回 JSON（${res.status}）:", "throw new Error(`API did not return JSON (${res.status}):"),
    ("if (out) out.textContent = `❌ Favorite列表加载失败：${e.message || e}`;", "if (out) out.textContent = `❌ Failed to load favorites: ${e.message || e}`;"),
    ("out.textContent = `❌ Favorite失败：${data.msg || 'unknown error'}`;", "out.textContent = `❌ Favorite failed: ${data.msg || 'unknown error'}`;"),
    ("out.textContent = `❌ Favorite失败：${e.message || e}`;", "out.textContent = `❌ Favorite failed: ${e.message || e}`;"),
    ("setWorkingStatus('正在替换Favorite地图');", "setWorkingStatus('Applying favorite map');"),
    ("out.textContent = `❌ 替换失败：${data.msg || 'unknown error'}`;", "out.textContent = `❌ Apply failed: ${data.msg || 'unknown error'}`;"),
    ("try { setState('idle', '已应用Favorite地图'); } catch (e) {}", "try { setState('idle', 'Applied favorite map'); } catch (e) {}"),
    ("out.textContent = `❌ 替换失败：${e.message || e}`;", "out.textContent = `❌ Apply failed: ${e.message || e}`;"),
    ("if (!window.confirm('确定删除这个Favorite吗？删除后不可恢复。')) return;", "if (!window.confirm('Delete this favorite? This cannot be undone.')) return;"),
    ("out.textContent = `❌ 删除失败：${data.msg || 'unknown error'}`;", "out.textContent = `❌ Delete failed: ${data.msg || 'unknown error'}`;"),
    ("out.textContent = `❌ 删除失败：${e.message || e}`;", "out.textContent = `❌ Delete failed: ${e.message || e}`;"),
    ("if (out) out.textContent = '请先选择一个资产';", "if (out) out.textContent = 'Please select an asset first';"),
    ("if (!window.confirm(`⚠️ 确定将 ${path} Reset为默认资产吗？`)) return;", "if (!window.confirm(`⚠️ Reset ${path} to default asset?`)) return;"),
    ("if (out) out.textContent = `❌ Reset失败：${data.msg || res.status}`;", "if (out) out.textContent = `❌ Reset failed: ${data.msg || res.status}`;"),
    ("if (out) out.textContent = `✅ 已Reset为默认资产：${path}`;", "if (out) out.textContent = `✅ Reset to default asset: ${path}`;"),
    ("if (out) out.textContent = `❌ Reset失败：${e}`;", "if (out) out.textContent = `❌ Reset failed: ${e}`;"),
    ("if (!window.confirm(`⚠️ 确定将 ${path} Rollback到上一版吗？`)) return;", "if (!window.confirm(`⚠️ Roll back ${path} to previous version?`)) return;"),
    ("if (out) out.textContent = `❌ Rollback失败：${data.msg || res.status}`;", "if (out) out.textContent = `❌ Rollback failed: ${data.msg || res.status}`;"),
    ("if (out) out.textContent = `✅ 已Rollback到上一版：${path}`;", "if (out) out.textContent = `✅ Rolled back to previous version: ${path}`;"),
    ("if (out) out.textContent = `❌ Rollback失败：${e}`;", "if (out) out.textContent = `❌ Rollback failed: ${e}`;"),
    # Guest panel
    ("暂无访客", "No guests online"),
    ("const name = agent.name || '未命名访客';", "const name = agent.name || 'Unnamed Guest';"),
    ("approved: '已授权'", "approved: 'Approved'"),
    ("pending: '待授权'", "pending: 'Pending'"),
    ("idle: '待命'", "idle: 'Idle'"),
    ("writing: '工作'", "writing: 'Working'"),
    ("researching: '调研'", "researching: 'Research'"),
    ("executing: '执行'", "executing: 'Executing'"),
    ("syncing: '同步'", "syncing: 'Syncing'"),
    ("error: '报警'", "error: 'Alert'"),
    ("alert('交换 skill 功能开发中')", "alert('Skill exchange feature coming soon')"),
    ("交换skill", "Exchange Skill"),
    ("alert((name || agentId) + ' 已Leave房间');", "alert((name || agentId) + ' has left the office');"),
    ("if (DEMO_MODE && (name === '尼卡' || name === '水星'))", "if (DEMO_MODE && (name === 'Nika' || name === 'Mercury'))"),
    ("alert(name + ' 已Leave房间（demo）');", "alert(name + ' left the office (demo)');"),
    ("alert('Leave失败：' + (data.msg || '未知Error'))", "alert('Leave failed: ' + (data.msg || 'Unknown error'))"),
    ("alert('请求失败：' + error)", "alert('Request failed: ' + error)"),
    ("alert('Approved该访客接入');", "alert('Guest access approved');"),
    ("alert('批准失败：' + (data.msg || '未知Error'))", "alert('Approve failed: ' + (data.msg || 'Unknown error'))"),
    ("alert('Rejected该访客');", "alert('Guest access rejected');"),
    ("alert('拒绝失败：' + (data.msg || '未知Error'))", "alert('Reject failed: ' + (data.msg || 'Unknown error'))"),
    # Demo agents
    ("{ agentId: 'demo_nika', name: '尼卡'", "{ agentId: 'demo_nika', name: 'Nika'"),
    ("bubbleText: '我在工作中'", "bubbleText: 'I am working'"),
    ("{ agentId: 'demo_mercury', name: '水星'", "{ agentId: 'demo_mercury', name: 'Mercury'"),
    ("bubbleText: '我去Break Room躺一下'", "bubbleText: 'Taking a break in the break room'"),
    # Agent pos comments
    ("// 区域坐标（海辛提供，左上-右下；这里的 x/y 作为 sprite 底部锚点坐标来用）", "// Area coordinates (top-left to bottom-right; x/y used as sprite bottom anchor)"),
    ("// Break Room域范围", "// Break Room area range"),
    ("// Work Area域范围", "// Work Area range"),
    ("// error 区域范围", "// Error area range"),
    ("// 非 demo 访客：仍用固定点位，避免每次轮询都抖动。", "// Non-demo guests: use fixed position to avoid jitter on each poll."),
    ("const isDemoNika = DEMO_MODE && (agent.agentId === 'demo_nika' || agent.name === '尼卡');", "const isDemoNika = DEMO_MODE && (agent.agentId === 'demo_nika' || agent.name === 'Nika');"),
    ("const isDemoMercury = DEMO_MODE && (agent.agentId === 'demo_mercury' || agent.name === '水星');", "const isDemoMercury = DEMO_MODE && (agent.agentId === 'demo_mercury' || agent.name === 'Mercury');"),
    ("if (DEMO_MODE && (agent.agentId === 'demo_mercury' || agent.name === '水星')) {", "if (DEMO_MODE && (agent.agentId === 'demo_mercury' || agent.name === 'Mercury')) {"),
    ("const yOffset = (DEMO_MODE && (agent.agentId === 'demo_mercury' || agent.name === '水星')) ? 10 : 0;", "const yOffset = (DEMO_MODE && (agent.agentId === 'demo_mercury' || agent.name === 'Mercury')) ? 10 : 0;"),
    ("const nameText = game.add.text(p.x, nameTextY, agent.name || '访客',", "const nameText = game.add.text(p.x, nameTextY, agent.name || 'Guest',"),
    ("g.nameText.setText(agent.name || '访客');", "g.nameText.setText(agent.name || 'Guest');"),
    # Demo bubble texts
    ("idle: ['我在Break Room待命', '先放松一下，等下一步任务', '我在休息充电中'],", "idle: ['Idling in the break room', 'Taking a breather, waiting for the next task', 'Resting and recharging'],"),
    ("writing: ['我在Work Area处理任务', '正在整理文档与执行中', 'Work Area专注推进中'],", "writing: ['Handling tasks at the work area', 'Organizing docs and executing', 'Focused and pushing forward'],"),
    ("researching: ['我在调研模式，搜集信息', '正在查资料和Verify线索', '研究中，稍后同步结论'],", "researching: ['In research mode, gathering info', 'Checking sources and verifying leads', 'Researching, will sync conclusions soon'],"),
    ("executing: ['执行中，正在跑流程', '我在Work Area推进任务', '正在把计划落地执行'],", "executing: ['Executing, running the workflow', 'Pushing tasks in the work area', 'Turning the plan into action'],"),
    ("syncing: ['同步中，马上更新Status', '正在同步进度到系统', '数据同步中请稍候'],", "syncing: ['Syncing, updating status shortly', 'Syncing progress to the system', 'Data sync in progress, please wait'],"),
    ("error: ['我在 bug 区排查问题', '检测到异常，正在修复', '报警中，先定位再处理']", "error: ['Debugging in the bug corner', 'Anomaly detected, fixing now', 'On alert — locating before fixing']"),
    # Demo state labels
    ("idle: '我去Break Room躺一下',", "idle: 'Heading to the break room',"),
    ("writing: '我在工作中',", "writing: 'I am working',"),
    ("researching: '我在调研中',", "researching: 'I am researching',"),
    ("executing: '我在执行任务',", "executing: 'I am executing tasks',"),
    ("syncing: '我在同步Status',", "syncing: 'I am syncing status',"),
    ("error: '出错了！我去报警区'", "error: 'Something went wrong! Heading to bug corner'"),
    # Welcome bubble
    ("zh: [`欢迎 ${newAgent.name} 来到Office～`,`Hi ${newAgent.name}，一起开工吧`,`${newAgent.name} 已Join，欢迎！`],",
     "en: [`Welcome ${newAgent.name} to the office!`,`Hi ${newAgent.name}, let's get to work`,`${newAgent.name} has joined — welcome!`],"),
    ("console.error('拉取访客列表失败:', error);", "console.error('Failed to fetch guest list:', error);"),
    # Misc comments
    ("// 初始化：先检测 WebP 支持，再启动游戏", "// Init: detect WebP support then start game"),
    ("// 检测 WebP 支持", "// Detect WebP support"),
    ("console.log('WebP 支持:', supportsWebP);", "console.log('WebP support:', supportsWebP);"),
    ("// 直接启动 Phaser，避免首屏被额外接口阻塞", "// Start Phaser directly to avoid blocking first paint"),
    ("// 非关键初始化延后到首屏之后，提升首开速度", "// Defer non-critical init after first paint for faster startup"),
    ("// 动态探测 flowers 精灵表帧规格（避免写死 65x65 导致显示比例异常）", "// Dynamically detect flowers spritesheet frame spec (avoid hardcoding 65x65 which causes scale issues)"),
    ("// 固定规则：花朵单帧 128x128，4x4", "// Fixed rule: flower frame 128x128, 4x4 grid"),
    ("console.warn('flowers 规格探测失败，使用默认 65x65', e);", "console.warn('flowers spec detection failed, using default 65x65', e);"),
    ("// 获取加载界面元素", "// Get loading overlay elements"),
    ("// Settings资源总数（全部首屏加载：Decoration也第一时间出现）", "// Total asset count (all loaded on first paint; decorations appear immediately)"),
    ("// 加载进度监听", "// Loading progress listener"),
    ("// 运行时 Gemini 配置（用于搬家/中介生图）", "// Runtime Gemini config (for Move In / AI Design image generation)"),
    ("// 动态替换后按最新素材识别：当前 writing 素材为 300x300 单帧", "// After dynamic replacement, identify by latest asset: current writing asset is 300x300 single frame"),
    ("// memo 底图固定走 png，避免某些端 webp 透明通道异常导致\"底图丢失\"", "// Memo background always uses PNG to avoid WebP transparency issues on some clients"),
    ("door: { x: 640, y: 550 }, // 墙的门（偏下 1/3 位置）", "door: { x: 640, y: 550 }, // Wall door (lower third)"),
    ("writing: { x: 320, y: 360 }, // 左 1/3 中间（办公桌）", "writing: { x: 320, y: 360 }, // Left third center (desk)"),
    ("researching: { x: 320, y: 360 }, // 左 1/3 中间（研究也在办公区", "researching: { x: 320, y: 360 }, // Left third center (research also at desk area)"),
    ("error: { x: 1066, y: 180 }, // 右 1/3 上 1/2（Server Room", "error: { x: 1066, y: 180 }, // Right third upper half (Server Room)"),
    ("breakroom: { x: IDLE_SOFA_ANCHOR.x, y: IDLE_SOFA_ANCHOR.y } // 与 sofa-idle-v3 同中心锚点", "breakroom: { x: IDLE_SOFA_ANCHOR.x, y: IDLE_SOFA_ANCHOR.y } // same center anchor as sofa-idle-v3"),
    ("// 创建 Star Character待命动画（每次先移除旧定义，确保不复用历史动画）", "// Create Star idle animation (remove old definition each time to avoid reusing stale animation)"),
    ("// 创建 6 个访客Character的循环 idle 动画（8帧循环）", "// Create 6 guest character looping idle animations (8-frame loop)"),
    ("// 加像素风小牌匾：Star's Pixel Office", "// Add pixel-style plaque: Star's Pixel Office"),
    ("// 牌匾两边加个小Decoration（跟随牌匾居中）", "// Add small decoration on both sides of plaque (centered with plaque)"),
    ("// 默认 idle: 静止第0帧", "// Default idle: static frame 0"),
    ("// 38 帧（0~37），避免沿用旧 192 帧导致疯狂闪烁", "// 38 frames (0~37), avoid using old 192-frame count which caused rapid flicker"),
    ("// 仅在确实存在可播放帧（>=1）时才创建同步动画，避免单帧素材触发播放异常", "// Only create sync animation when there are playable frames (>=1) to avoid single-frame asset errors"),
    ("// guest agent 将由 /agents 动态拉取并渲染到右侧访客列表", "// Guest agents are dynamically fetched from /agents and rendered in the right guest list"),
    ("// 允许手机端\"拖动/滑动\"来移动视野（本质：移动 Phaser Camera）", "// Allow mobile drag/swipe to pan the view (moves Phaser Camera)"),
    ("// iPhone 等触屏设备默认开启；桌面端默认Close（可手动开）。", "// Enabled by default on touch devices; disabled by default on desktop (can be enabled manually)."),
    ("// 手机上：锁定\"Office画布高度 = 2/3 区域高度\"，", "// Mobile: lock office canvas height = 2/3 viewport height,"),
    ("// 让世界坐标在竖向恰好看满（不需要上下拖），只保留横向拖动浏览左右。", "// so world fits vertically (no vertical drag needed), only horizontal pan."),
    ("// 记录初始是否已手动平移（避免 resize 时把用户拖好的位置Reset）", "// Track if user has manually panned (avoid resetting position on resize)"),
    ("// 关键：先按高度 fit，再看是否需要按宽度微调，", "// Key: fit by height first, then check if width adjustment needed,"),
    ("// 保证既不会让画面歪，又能左右拖到最左最右边缘不被裁。", "// ensuring canvas stays straight and horizontal pan reaches both edges."),
    ("// 按 candidateZoom 计算：viewport 在世界坐标里的宽高", "// Calculate with candidateZoom: viewport width/height in world coordinates"),
    ("// 仅在未手动平移过时才居中（避免把用户拖好的位置冲掉）", "// Only center if user has not manually panned (avoid overriding user position)"),
    ("// 手机端旋转屏幕/地址栏伸缩时，重算 zoom + 夹紧 camera", "// Recalculate zoom and clamp camera on mobile rotate / address bar resize"),
    ("const info = on ? '视野拖动已开启（可左右拖动画布）' : '视野拖动已Close（点击左上角\"移动视野\"可开启）';", "const info = on ? 'Pan enabled (drag canvas left/right)' : 'Pan disabled (click \"Pan View\" in top-left to enable)';"),
    ("statusText.textContent = `Status：[${(STATES[currentState] && STATES[currentState].name) || '待命'}] ${info}`;", "statusText.textContent = `Status: [${(STATES[currentState] && STATES[currentState].name) || 'Idle'}] ${info}`;"),
    ("// 手机端默认Close拖动画面：由左上角\"移动视野\"开关显式开启", "// Mobile: pan disabled by default; enabled by the top-left 'Pan View' toggle"),
    ("// iOS/Safari 手势策略：", "// iOS/Safari gesture strategy:"),
    ("// - 保留垂直滚动（让页面能下滑看三个面板）", "// - Keep vertical scroll (allows page to scroll down to panels)"),
    ("// - 水平方向拖动时才阻止默认行为，并转为 camera 横向平移", "// - Only block default on horizontal drag; convert to camera horizontal pan"),
    ("// 说明：iOS 对 pointer + touch-action 支持存在机型差异，所以这里加一套原生 touch 兜底。", "// Note: iOS pointer + touch-action support varies by device, so we add native touch fallback."),
    ("// 手机端允许页面自然滚动，避免\"不能滑动\"", "// Allow natural page scroll on mobile to avoid 'can't scroll' issues"),
    ("// 横向拖动交给Office视野；阻止浏览器默认滚动", "// Horizontal drag handled by office view; prevent browser default scroll"),
    ("// lock==='y' 时不阻止默认，交给页面纵向滚动", "// When lock==='y', don't block default — let page scroll vertically"),
    ("// 手机端优先\"横向拖动看Office\"，纵向手势留给页面滚动看下方面板。", "// Mobile: prioritize horizontal office pan; vertical gestures go to page scroll."),
    ("// 手指向右拖，视野跟着向右看：camera scroll 向左减小（反向）", "// Drag right → view moves right: camera scroll decreases (inverted)"),
    ("// 桌面端保留自由二维拖动", "// Desktop: free 2D drag retained"),
    ("// 加载昨日 memo", "// Load yesterday memo"),
    ("// 兜底：非 idle 时确保机房动画在播，idle 时静止", "// Fallback: ensure server room animation plays when not idle, static when idle"),
    ("// error Status：显示 bug 动画，并在两点之间来回移动", "// Error state: show bug animation, ping-pong between two points"),
    ("// 固定在原地（按需求Cancel error 移动路径）", "// Fixed in place (movement path cancelled per requirements)"),
    ("// 冒气泡", "// Show bubble"),
    ("// 猫的气泡（频率低）", "// Cat bubble (low frequency)"),
    ("// 打字机效果", "// Typewriter effect"),
    ("// 移动 + 小踱步", "// Move + wander"),
    ("// guest 随机想法泡泡", "// Guest random thought bubbles"),
    ("// demo 平滑移动时：让气泡每帧跟随Character锚点（避免 tween 时气泡滞留在旧位置）", "// Demo smooth move: make bubble follow character anchor each frame (avoid bubble lagging during tween)"),
    ("// guest 列表会定时刷新", "// Guest list refreshes periodically"),
    ("// 不论 changed 与否，都按服务端最新Status强制一次视觉同步，避免动画卡旧Status", "// Regardless of change, force a visual sync to latest server state to avoid animation sticking"),
    ("typewriterTarget = 'Status更新异常，正在恢复...';", "typewriterTarget = 'Status update error, recovering...';"),
    ("typewriterTarget = '连接失败，正在重试...';", "typewriterTarget = 'Connection failed, retrying...';"),
    ("// idle 时锁定位置（不走任何移动路径）", "// Lock position when idle (no movement path)"),
    ("if (currentState === 'idle') return; // idle 不显示气泡（可按需开启）", "if (currentState === 'idle') return; // idle does not show bubble (can be enabled if needed)"),
    ("// 只做手机端稍微调大一点，避免发糊", "// Slightly larger on mobile to avoid blur"),
    ("// 假 Agent 气泡逻辑已移除，统一以真实 /agents 数据为准", "// Fake agent bubble logic removed; all data now from real /agents endpoint"),
    ("// 启动游戏", "// Start game"),
    # Misc remaining
    ("const IDLE_SOFA_ANCHOR = { x: 798, y: 272 }; // 统一中心锚点（原 sofa 左上 670,144 的中心）", "const IDLE_SOFA_ANCHOR = { x: 798, y: 272 }; // unified center anchor (center of sofa top-left 670,144)"),
    ("const IDLE_STAR_SCALE = 1.0; // star idle 改为256帧原生显示，不再放大", "const IDLE_STAR_SCALE = 1.0; // star idle uses native 256-frame display, no longer scaled up"),
    ("// flowers 精灵表规格：固定单帧 128x128，4x4", "// flowers spritesheet spec: fixed 128x128 single frame, 4x4 grid"),
    ("// 坐标以服务端为准；清理历史本地缓存，避免把素材挪飞", "// Use server-side coordinates; clear local cache to avoid asset misplacement"),
    ("// 默认走更稳的Model档（quality），避免部分通道不支持 fast Model时报错", "// Default to stable model tier (quality) to avoid errors on channels that don't support fast model"),
    ("let lastSeenGuestIds = new Set(); // 用于检测新Join的访客，触发欢迎气泡", "let lastSeenGuestIds = new Set(); // detect newly joined guests to trigger welcome bubble"),
    ("// Status控制栏函数（用于测试）", "// Status control bar functions (for testing)"),
    # Asset display feedback
    ("if (out) out.textContent = nextVisible ? `✅ 已显示：${p}` : `🙈 已隐藏：${p}`;", "if (out) out.textContent = nextVisible ? `✅ Shown: ${p}` : `🙈 Hidden: ${p}`;"),
    ("// 统一显示后端全部资产（不再区分已加载/全部）", "// Show all backend assets uniformly (no longer split between loaded/all)"),
    ("if (idx >= 0) return idx; // 0~3: 四个主Status最前", "if (idx >= 0) return idx; // 0~3: four main states at the top"),
    ("// 按钮素材最不重要：统一沉到列表末尾", "// Button assets are least important: push to end of list"),
    ("if (p.includes('guest_anim_')) return 999; // guest 动画靠后", "if (p.includes('guest_anim_')) return 999; // guest animations pushed back"),
    # Upload feedback
    ("out.textContent = `✅ 已Upload（动图→${toType}）：${data.path} ｜ ${data.converted.frames}帧", "out.textContent = `✅ Uploaded (animated→${toType}): ${data.path} | ${data.converted.frames} frames"),
    ("out.textContent = `✅ 已Upload：${data.path}`;", "out.textContent = `✅ Uploaded: ${data.path}`;"),
    ("if (hasFile) out.textContent += ' ｜ ✅ 已Upload并刷新';", "if (hasFile) out.textContent += ' | ✅ Uploaded and refreshed';"),
    ("else out.textContent = '✅ 已Confirm并刷新';", "else out.textContent = '✅ Confirmed and refreshed';"),
    ("// 刷新前CloseSidebar，行为与地图替换一致", "// Close sidebar before refresh, consistent with map replacement behavior"),
    # Scene texture comments
    ("// 背景做特殊映射：即使纹理 key 已变成 office_bg_live_xxx，也能稳定定位到背景对象", "// Background uses special mapping: even if texture key changes to office_bg_live_xxx, reliably locates background object"),
    ("// 优先：后端持久化坐标；Rollback：后端默认坐标；最后：本地内存覆盖", "// Priority: backend persisted coords; fallback: backend defaults; last: local memory override"),
    ("// 先尝试资产路径命中（推荐持久化键，优先级最高）", "// First try asset path match (recommended persist key, highest priority)"),
    ("// 再尝试 textureKey 命中（兼容旧数据）", "// Then try textureKey match (compat with old data)"),
    ("// 最后按 stem 模糊匹配（处理 webp/png 或 live key 差异）", "// Finally try stem fuzzy match (handle webp/png or live key differences)"),
    ("// 二次点击同一资产 = Cancel选择", "// Double-clicking same asset = cancel selection"),
    ("// 优先用文件命名约定推断（不写死具体尺寸）", "// Infer from filename convention (avoid hardcoding dimensions)"),
    ("// 先看命名是否属于精灵表", "// Check if name indicates a spritesheet"),
    ("// 仅返回\"是精灵表\"的信号，单帧尺寸后续自动推断", "// Only return 'is spritesheet' signal; single frame size inferred later"),
    ("// 常见核心资产优先用显式提示（避免误判）", "// Common core assets use explicit hints first (avoid misdetection)"),
    ("// 通用推断：枚举可整除候选，偏好 cols≈8、帧尺寸适中、近似方形", "// General inference: enumerate divisible candidates, prefer cols≈8, moderate frame size, near-square"),
    ("// 判断是否可能是精灵表：整图宽高至少是单帧的整数倍，且总帧数>1", "// Determine if likely spritesheet: total image width/height is integer multiple of frame, total frames >1"),
    ("// Scene渲染可能稍晚，做一次延迟抓取", "// Scene may render slightly late; do a delayed capture"),
    ("console.warn('替换Scene纹理失败(setTexture):', e);", "console.warn('Scene texture replacement failed (setTexture):', e);"),
    ("// 按扩展名用对应 loader", "// Use appropriate loader by file extension"),
    ("console.warn('替换Scene纹理失败(load):', e);", "console.warn('Scene texture replacement failed (load):', e);"),
    ("if (!path) { out.textContent = '请先选中一个资产路径'; return false; }", "if (!path) { out.textContent = 'Please select an asset path first'; return false; }"),
    ("// 全自动：后端识别并切帧", "// Fully automatic: backend detects and slices frames"),
    ("// 静态图兜底切法", "// Static image fallback slicing"),
    # isDemo check
    ("const isDemo = !!agent.isDemo || (DEMO_MODE && (id === 'demo_nika' || id === 'demo_mercury' || agent.name === '尼卡' || ag",
     "const isDemo = !!agent.isDemo || (DEMO_MODE && (id === 'demo_nika' || id === 'demo_mercury' || agent.name === 'Nika' || ag"),
    ("// 优先用图标：demo visitor 有专门映射", "// Prefer icon: demo visitor has dedicated mapping"),
    ("// 统一使用动态像素Character，避免依赖已删除的 demo 静态图", "// Use dynamic pixel character uniformly to avoid depending on deleted demo static images"),
    ("// 非 demo 访客：优先用动画精灵（guest_anim_x），其次静态图，兜底星星", "// Non-demo guests: prefer animated sprite (guest_anim_x), then static image, fallback star"),
    ("// 先确定Character索引（1-6）", "// Determine character index (1-6) first"),
    ("// demo 水星下移 10px（仅 demo_mercury）", "// Demo Mercury moved down 10px (demo_mercury only)"),
    ("// demo：平滑移动（避免闪现）；非 demo：保持稳定位置（避免轮询抖动）", "// Demo: smooth movement (avoid flash); non-demo: stable position (avoid poll jitter)"),
    ("const duration = 2000 + Math.floor(Math.random() * 1000); // 2~3s 走路感", "const duration = 2000 + Math.floor(Math.random() * 1000); // 2~3s walking feel"),
    ("// 删除消失的 agent + 清理其气泡/tween", "// Remove disappeared agents and clean up their bubbles/tweens"),
    ("// demo 气泡：优先展示与Status对应的内容，便于Verify\"Status→区域→气泡\"链路", "// Demo bubble: prioritize state-matching content to make state→area→bubble chain easy to verify"),
    ("// 气泡位置：demo 维持原逻辑；真实访客放在\"名字上方\"，避免压Character也避免压名字", "// Bubble position: demo keeps original logic; real guests placed above name tag, avoid covering character or name"),
    ("// 让气泡跟随 sprite 锚点（用于 demo 平滑移动时也保持贴合）", "// Make bubble follow sprite anchor (for demo smooth movement, keep bubble attached)"),
    ("// 按海辛需求：每 8 秒切换一次Status", "// Per design spec: switch state every 8 seconds"),
    ("// 确保两位 demo Character不会总是同一个Status（增加可观测性）", "// Ensure two demo characters don't always share the same state (improve observability)"),
    ("const next1 = pickJs(next0); // 尽量不同", "const next1 = pickJs(next0); // try to differ"),
    ("// Status切换时：每一位 demo 都立即冒泡（强制），用于清晰Verify链路", "// On state change: each demo immediately bubbles (forced) to clearly verify the chain"),
    ("// 找出Status实际变了的 demo visitor，给他们强制冒泡", "// Find demo visitors whose state actually changed, force bubble them"),
    ("// 直接冒泡", "// Bubble directly"),
    ("} catch (e) { console.error('强制冒泡失败:', e); }", "} catch (e) { console.error('Forced bubble failed:', e); }"),
    ("// demo 随机Status先更新（不依赖后端）", "// Update demo random state first (independent of backend)"),
    ("// 无论后端返回是否为数组，demo=1 都应保证本地 demo 访客可见", "// Regardless of backend response, demo=1 must ensure local demo guests are visible"),
    ("// 新访客检测：触发 Star 欢迎气泡（只欢迎真实访客，不欢迎 demo）", "// New guest detection: trigger Star welcome bubble (real guests only, not demo)"),
    ("// 首次初始化不欢迎，避免刷新页面就刷屏", "// Don't welcome on first init to avoid flooding on page refresh"),
    ("// 只欢迎第一个新来的（避免同一时刻多人Join刷屏）", "// Only welcome the first new arrival (avoid flood when multiple join simultaneously)"),
    ("// 临时将 currentState 视为 writing 以允许 showBubble 展示", "// Temporarily treat currentState as writing to allow showBubble to display"),
    ("// 临时更换 bubble 文案", "// Temporarily replace bubble text"),
    ("// 还原", "// Restore"),
]

process(index_path, idx_repl)

# ─── join.html ──────────────────────────────────────────────────────────────
join_path = os.path.join(BASE, 'join.html')
with open(join_path, 'r', encoding='utf-8') as f:
    jc = f.read()

join_repl = [
    # Common UI strings
    ('加入办公室', 'Join the Office'),
    ('访客加入', 'Guest Join'),
    ('接入密钥', 'Join Key'),
    ('请输入接入密钥', 'Enter join key'),
    ('你的名字', 'Your Name'),
    ('请输入名字', 'Enter your name'),
    ('正在加入...', 'Joining...'),
    ('加入成功', 'Joined successfully'),
    ('加入失败', 'Join failed'),
    ('密钥无效', 'Invalid key'),
    ('名字不能为空', 'Name cannot be empty'),
    ('密钥不能为空', 'Key cannot be empty'),
    ('已在办公室', 'Already in office'),
    ('办公室已满', 'Office is full'),
    ('密钥已过期', 'Key has expired'),
    ('连接中...', 'Connecting...'),
    ('已连接', 'Connected'),
    ('断开连接', 'Disconnected'),
    ('重新连接', 'Reconnect'),
    ('状态推送', 'Status Push'),
    ('推送间隔', 'Push interval'),
    ('开始推送', 'Start Pushing'),
    ('停止推送', 'Stop Pushing'),
    ('当前状态', 'Current Status'),
    ('待命', 'Idle'),
    ('工作中', 'Working'),
    ('研究中', 'Researching'),
    ('执行中', 'Executing'),
    ('同步中', 'Syncing'),
    ('出错了', 'Error'),
    ('状态描述', 'Status Description'),
    ('请输入描述', 'Enter description'),
    ('更新状态', 'Update Status'),
    ('访客指南', 'Guest Guide'),
    ('复制链接', 'Copy Link'),
    ('分享', 'Share'),
    ('加入', 'Join'),
]
for old, new in join_repl:
    jc = jc.replace(old, new)
with open(join_path, 'w', encoding='utf-8') as f:
    f.write(jc)
n = len(re.findall(r'[\u4e00-\u9fff]', jc))
print(f'join.html: {n} remaining')

# ─── invite.html ─────────────────────────────────────────────────────────────
invite_path = os.path.join(BASE, 'invite.html')
with open(invite_path, 'r', encoding='utf-8') as f:
    ic = f.read()

invite_repl = [
    ('邀请访客', 'Invite Guest'),
    ('邀请链接', 'Invite Link'),
    ('接入密钥', 'Join Key'),
    ('复制', 'Copy'),
    ('已复制', 'Copied'),
    ('生成新密钥', 'Generate New Key'),
    ('密钥列表', 'Key List'),
    ('无密钥', 'No keys'),
    ('添加密钥', 'Add Key'),
    ('删除', 'Delete'),
    ('最大并发', 'Max Concurrent'),
    ('可复用', 'Reusable'),
    ('已使用', 'Used'),
    ('未使用', 'Unused'),
    ('访客指南', 'Guest Guide'),
    ('如何加入', 'How to Join'),
    ('步骤', 'Step'),
    ('下载脚本', 'Download Script'),
    ('填写信息', 'Fill in Details'),
    ('运行脚本', 'Run Script'),
    ('你的访客将出现在办公室里', 'Your guest will appear in the office'),
    ('办公室地址', 'Office URL'),
    ('分享给访客', 'Share with guest'),
]
for old, new in invite_repl:
    ic = ic.replace(old, new)
with open(invite_path, 'w', encoding='utf-8') as f:
    f.write(ic)
n = len(re.findall(r'[\u4e00-\u9fff]', ic))
print(f'invite.html: {n} remaining')

# ─── office-agent-push.py ────────────────────────────────────────────────────
push_path = os.path.join(BASE, 'office-agent-push.py')
with open(push_path, 'r', encoding='utf-8') as f:
    pc = f.read()

push_repl = [
    ('# 填写你的信息', '# Fill in your details'),
    ('# 你的接入密钥', '# Your join key'),
    ('# 你的名字（显示在看板上）', '# Your display name (shown on dashboard)'),
    ('# 办公室地址', '# Office URL'),
    ('# 状态推送间隔（秒）', '# Status push interval (seconds)'),
    ('# 当前工作状态', '# Current work state'),
    ('# 状态描述', '# Status description'),
    ('# 有效状态', '# Valid states'),
    ('# 加入办公室', '# Join the office'),
    ('# 推送状态', '# Push status'),
    ('# 离开办公室', '# Leave the office'),
    ('# 主循环', '# Main loop'),
    ('# 捕获退出信号', '# Catch exit signal'),
    ('加入中...', 'Joining...'),
    ('加入成功', 'Joined successfully'),
    ('加入失败', 'Join failed'),
    ('推送状态中...', 'Pushing status...'),
    ('推送失败', 'Push failed'),
    ('离开办公室...', 'Leaving office...'),
    ('离开成功', 'Left successfully'),
    ('按 Ctrl+C 退出', 'Press Ctrl+C to exit'),
    ('已退出', 'Exited'),
    ('连接失败', 'Connection failed'),
    ('重试中...', 'Retrying...'),
    ('接入密钥', 'Join key'),
    ('显示名称', 'Display name'),
    ('待命中', 'Standing by'),
    ('工作中', 'Working'),
    ('研究中', 'Researching'),
    ('执行中', 'Executing'),
    ('同步中', 'Syncing'),
    ('出错了', 'Error'),
    ('正在工作', 'Working'),
    ('等待中', 'Waiting'),
]
for old, new in push_repl:
    pc = pc.replace(old, new)
with open(push_path, 'w', encoding='utf-8') as f:
    f.write(pc)
n = len(re.findall(r'[\u4e00-\u9fff]', pc))
print(f'office-agent-push.py: {n} remaining')

print('\nAll done.')
